version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: >
      sh -c "python manage.py migrate --noinput &&
         python manage.py collectstatic --noinput &&
         gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: 