# Generated by Django 5.1.7 on 2025-05-03 17:27

import JobMatrix.models
import JobMatrix.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_resume',
            field=models.FileField(blank=True, db_column='applicant_resume', max_length=255, null=True, storage=JobMatrix.storage_backends.MediaStorage(), upload_to=JobMatrix.models.Applicant.resume_upload_to),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.FileField(blank=True, db_column='company_image', max_length=255, null=True, storage=JobMatrix.storage_backends.MediaStorage(), upload_to=JobMatrix.models.Company.company_image_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_photo',
            field=models.FileField(blank=True, db_column='user_profile_photo', max_length=255, null=True, storage=JobMatrix.storage_backends.MediaStorage(), upload_to=JobMatrix.models.User.user_profile_photo_upload_to),
        ),
    ] 